models/contact.py
from utils.db import db

class Contact(db.Model):
    id= db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contact import contacts
from flask_sqlalchemy import SQLAlchemy
from config  import DATABASE_CONNECTION_URI
app = Flask(__name__)

app.secret_key = "Secret__key"

app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

app.config['SQLALCHEMY_POOL_SIZE'] = 10
app.config['SQLALCHEMY_MAX_OVERFLOW'] = 10
app.config['SQLALCHEMY_POOL_TIMEOUT'] = 5
app.config['SQLALCHEMY_POOL_RECYCLE'] = 10

SQLAlchemy (app)

app.register_blueprint(contacts)

routes/contact.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint('contacts',__name__)

@contacts.route("/")
def index():
    contacts = Contact.query.all()
    db.session.close()
    return render_template('index.html', contacts=contacts, contact = "")

@contacts.route('/new', methods=['POST'])
def add_contact():
    fullname = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    print(fullname, " ", email, " ", phone)

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()
    flash("contact added successfully!")
    return redirect(url_for('contacts.index'))


@contacts.route('/update/<id>', methods= ['GET', 'POST'])
def update(id):
    if request.method == 'GET':
        print("metodo get")
        contact = Contact.query.get(id)
        db.session.close()
        flash("contact found successfully!")
        return render_template('index.html', contacts="", contact_update = contact)

    if request.method == 'POST':
        print("metodo post")
        contact = Contact.query.get(id)
        
        contact.fullname = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']

        db.session.commit()
        db.session.close()
        flash("contact update successfully!")
        return redirect(url_for('contacts.index'))


@contacts.route('/delete/<id>')
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()
    db.session.close()
    flash("contact deleted successfully!")
    return redirect(url_for('contacts.index'))


@contacts.route("/about")
def about():

    return render_template('about.html')

templates/about.html
{% extends 'layout.html'%}
{%block content %}

<body>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus consequuntur autem nulla fugit repudiandae? Rem voluptate, iure commodi quaerat dolores odit eum itaque corporis recusandae deleniti magni, voluptatibus enim deserunt?
    
</body>
{% endblock%}

templates/index.html
{% extends 'layout.html'%}
{%block content %}



    <h1>home page</h1>   
    <div class="row">
        <div class="col-md-5">
            {% if contact_update %}      

            <form id="form_update", action="/update/{{contact_update.id}}" method="POST" class="card bg-dark text-light" >
                <div class="card-body p-4">
                    <div class="mb-3">
                        <label for="id">ID</label>
                        <input type="text" id="id" name="id" placeholder="field autocomplete" value = "{{contact_update.id}}"class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="id">Write your new fullname</label>
                        <input type="text" name="fullname" placeholder="Write your fullname" value = "{{contact_update.fullname}}" class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="id">Write your new email</label>
                        <input type="text" name="email" placeholder="Write your email" value = "{{contact_update.email}}" class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="id">Write your new phone</label>
                        <input type="text" name="phone" placeholder="Write your phone"value = "{{contact_update.phone}}"class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                    <button class="btn btn-primary" method= "POST">Update</button>       
                </div>          
            </form>

        {% else %} 
            <form id="form_new", action="/new" method="POST" class="card bg-dark text-light" >
                <div class="card-body p-4">
                    <div class="mb-3">
                        <label for="id">Write your new fullname</label>
                        <input type="text" name="fullname" placeholder="Write your fullname" class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="id">Write your new email</label>
                        <input type="text" name="email" placeholder="Write your email" class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                    <div class="mb-3">
                        <label for="id">Write your new phone</label>
                        <input type="text" name="phone" placeholder="Write your phone" class="form-control rounded-0 bg-dark border-0 text-white">
                    </div>
                </div>    
                <button class="btn btn-primary">Save</button>
            </form>
        {% endif%}

        </div>
        <div class="col-md-7">
            
                {% for contact in contacts%}
                <div class="card-mb-1   text-white bg-dark">
                    <div class="card-bady p-2">
   
                        <div class="d-flex justify-content-between">
                            <h5>{{contact.fullname}}</h5>
                            <div>
                                <a href="{{ url_for('contacts.update', id= contact.id)}}" class=" btn btn-black btn-sm text-white rounded-0">Update</a>
                                <a href="{{ url_for('contacts.delete', id= contact.id)}}" class=" btn btn-danger btn-sm rounded-0">Delete</a>
                            </div>
                        </div>
                        <p>{{contact.email}}</p>
                        <p>{{contact.phone}}</p>
                    </div>
                </div>
                {% endfor %}
            
        </div>
    </div>
   
    
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQLAlchemy CRUD </title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" 
integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"  crossorigin="anonymous">
<link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}">
</head>
<body>

    {% include('partials/_navbar.html')%}

    
    
    <div class="container p-2">
        {% include('partials/_message.html')%}
        {% block content %}

        {% endblock %}
    </div>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

templates/partials/_message.html
{% with messages = get_flashed_messages() %}

{% if messages %}
    {% for message in messages%}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
    {% endfor %}
{% endif %}

{% endwith%}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand" href="/">SQLAlchemy CRUD</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/about">About</a>
          </li>
          
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>